# Generated by Django 5.0.1 on 2024-02-04 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_table_alter_bookauthor_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='create_at',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='star_given',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
